### PR TITLE
Update documentation and project description

### PR DESCRIPTION
**Pull request by sergeyklay**
- Update documentation and project description
- Move screenshots to the `screenshots` directory
- Create `screenshots/README.md` with screenshots description

To see how README.md will look refer to:
https://github.com/sergeyklay/ac-php/blob/update-documentation/README.md

### CODE REVIEW

**Comment by sergeyklay** [comment]
@xcwen Could you please enable Travis CI integration so that I can provide a configuration to run tests each pull request.

**Comment by xcwen** [comment]
@xcwen Could you please enable Travis CI integration so that I can provide a configuration to run tests each pull request.
-------------
you do it :>

**Comment by sergeyklay** [comment]
@xcwen I have no access rights to configure this repo on Travis CI. Only owner has access rights to do it  

Please visit https://travis-ci.com/ and use this button

image

**Comment by sergeyklay** [comment]
@dreamsxin Could you please help use here with English (and Travis CI) :pray:

**Comment by xcwen** [comment]
Travis CI , config is ok.
image

**Comment by sergeyklay** [comment]
Thank you

**Pull request merged**
