### PR TITLE
Fix a typo of link

### PR DESCRIPTION
**Pull request by suzuki**
## About

I found a typo in README.md

- incorrect
    - `FQA`
- correct
    - `FAQ`

## Links

- https://github.com/xcwen/ac-php/blob/master/README.md#faq

### CODE REVIEW

**Comment by xcwen** [comment]
ok .

**Comment by suzuki** [comment]
@xcwen Hmm, my fix removed from latest `master` branch.

**Comment by xcwen** [comment]
:>

**Comment by xcwen** [comment]
fix

**Pull request merged**
